apiVersion: v1
kind: Service
metadata:
  name: devops-learning-hub-service
spec:
  type: NodePort
  selector:
    app: devops-learning-hub
  ports:
    - port: 80
      # target port is the port on which our application is running.
      targetPort: 8000
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007